name: S3 Auto Update

on:
  push:
    branches: [ main ] # Change to your default branch if different
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Sync files to S3 bucket
      run: |
        # Install AWS CLI if not already present
        sudo apt-get install -y awscli
        
        # Sync files (excluding .git directory)
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --delete
