name: S3 Auto Update

on:
  push:
    branches: [ main ] # Change to your default branch if different
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y unzip
        
        # Download and install AWS CLI v2
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        
        # Verify installation
        aws --version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'ap-south-1' }}

    - name: Sync files to S3 bucket
      run: |
        # Sync files (excluding .git directory)
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --delete
