name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify AWS CLI Installation
        run: aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check AWS Credentials
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        run: aws s3 ls

      - name: Debug Directory Path
        run: ls -la ./your-folder

      - name: Upload Files to S3
        run: aws s3 sync ./your-folder s3://gh-actio --delete
